### ISSUE TITLE
Remove APIDateFormat, RFC3339 for everyone!

### ISSUE THREAD

**Issue by 200sc** [itchio/go-itchio#2]
If a server was to actually return the types that go-itchio says it expects, and then butler or another service using go-itchio tried to use those types, time parsing would fail (causing e.g. butler to crash) because `APIDateFormat` isn't `RFC3999`, which is what time.Time [will be encoded as in json](https://golang.org/src/time/time.go?s=36257:36300#L1199).

This means that servers trying to respond to butlers requests right now would have to duplicate the contents of the `types.go` file and change the `time.Time` values into something that can have the right format, or otherwise wrap all types so that they could write their own `MarshalJSON` function.

If every type (with timestamps) in the package had a `MarshalJSON` function which formatted their times using `APIDateFormat`, this would be resolved without breaking the API, and a breaking API change for DYI could be to move out the `CreatedAt`/`UpdatedAt` pairs into a type that would be embedded in the types that use it, and just `MarshalJSON` that and the `CreatedAt`/`PublishedAt` field for a game.

An alternative solution would be somehow working with the mapstructure package to support RFC 3999, as [this line](https://github.com/itchio/go-itchio/blob/master/http_helpers.go#L189) is currently the one enforcing that json received uses APIDateFormat.

**Comment by fasterthanlime** [comment]
I've discussed this with @GranPC and @leafo and we're working on an upstream fix instead - ie. a version of the itch.io API that will use RFC-3339 (not 3999! pesky RFC numbers..) throughout.

**Comment by 200sc** [comment]
Whoops, yes 3339. Sounds good.

**Comment by fasterthanlime** [comment]
Closed in https://github.com/itchio/go-itchio/commit/6758acb843150e3d72f9634d831a88c0f692cd16

**Comment by Guard13007** [comment]
@fasterthanlime You told me to follow this issue to watch out for a change in the API for version checking.

https://itch.io/api/1/x/wharf/latest is specifically what I'm interested in, and it looks like this change doesn't affect that, correct? Or should I be watching a different issue?

**Comment by fasterthanlime** [comment]
@Guard13007 the new endpoint would be:

https://api.itch.io/wharf/latest?channel_name=windows-amd64&target=fasterthanlime/kitch

**Comment by Guard13007** [comment]
Am I correct in guessing the version number and x are to do with it being an experimental version and that's why they are removed? Or is there some other reasoning? How long will the old endpoints be supported? What happens if there is a new version?

**Comment by 200sc** [comment]
I'm also concerned about version numbers-- I assumed the new versions' endpoints would use an `api/2` prefix or some sort.

**Comment by fasterthanlime** [comment]
I replied in a hurry (and am doing it again), I should've been clearer.

Here's the short version:

First off, **v2 is not documented yet**, so it should not be used yet for anything in production.

When we do document it, we'll explain that:

  * v1 is legacy, it grew organically, we didn't have a chance to consider its design as a whole
  * from v2 on:
    * https://api.itch.io/ will serve the latest API version
    * it should be relatively stable (since we got a chance to do a lot of cleanups between v1 and v2)
    * API users are encouraged to use a HTTP header to "pin" to the version of the API they want
  * since there are games already released that use API v1, we plan on maintaining it for the foreseeable future (that goes for all API versions)
    * in rare instances, we may have to deprecate endpoints - in that case, we'll announce it in advance, leaving a generous window for developers to move on to another endpoint. We'll try to avoid that as much as possible

We deployed v2 before documenting it because we needed some cleanups and new endpoints for:

  * https://github.com/itchio/itch-setup
  * https://github.com/itchio/itch v25
  * http://docs.itch.ovh/butlerd/master/
  * https://broth.itch.ovh/
  * the backend of https://github.com/itchio/butler (not public)

It's been a rough year-ish of cleanups and reliability work, I promise everything will be documented eventually!
